### ISSUE TITLE
Problem with New Warping System

### ISSUE THREAD

**Issue by Chilledchewbacca** [Fabricio20/HubBasics#10]
Hey Fabrico,

Sorry to hear about your computer dude, i hope you get it up and running again soon :)

I've Encountered quite a serious Bug with the new warp system that you've implemented, it's completely overridden the warp system i already had in place (essentials warps) and now non of my users can warp because they do not have permissions, it is definitely hub basics causing this problem.

Can you please add an option in the config under the warps section to be able to completely disable it please? so it will run as it did before you implemented it

Thanks, Good luck with your pc!

**Comment by Fabricio20** [comment]
I thinked about this possibility, it Will take a bit to me to get The pc and fiz, for nos use my system until i get another pc to fiz this.

**Comment by Fabricio20** [comment]
Fix* now*

**Comment by Chilledchewbacca** [comment]
what is the permission node for your warping system? 
you haven't yet put it into the permissions list, i was thinking i could do this until you got it sorted but i couldn't figure out the permissions required.

**Comment by Fabricio20** [comment]
If i'm not wrong it os HubBasics.Warps.Name

**Comment by Fabricio20** [comment]
Is*

**Comment by Chilledchewbacca** [comment]
Thanks i'll try it out :)

**Comment by Fabricio20** [comment]
Fixed on the latest commit!
