### ISSUE TITLE
${Player.Name} Not working

### ISSUE THREAD

**Issue by wildmaster84** [Fabricio20/HubBasics#101]
${Player.Name} in the join/leave section wont work, I tried ${Player.Name} %{Player.Name} %layer.Name% %player% and still wont work, please help.

Join: '&6[&2+&6] &9${Player.Name} &6has joined the server.'
Leave: '&6[&c-&6] &9${Player.Name} &6has left the server.'
Worlds:
  world: '%player% joined &bSkyBlock&6.'

**Comment by Fabricio20** [comment]
can you try `${Player.DisplayName}`?

Some of the replaces are here: https://github.com/Fabricio20/HubBasics/blob/master/HB-Spigot/src/main/java/net/notfab/hubbasics/spigot/utils/PlaceHolderUtil.java#L39

**Comment by wildmaster84** [comment]
I just tried it and it still don't work

**Comment by wildmaster84** [comment]
oops xD

**Comment by Fabricio20** [comment]
Should be working as of today.
