### ISSUE TITLE
Plugin not loading items

### ISSUE THREAD

**Issue by bichbichbich** [Fabricio20/HubBasics#113]
ItemManager is unable to load custom items. Any idea what could cause it / how to fix it?

<img width="570" alt="putty_14m3xVaqpB" src="https://user-images.githubusercontent.com/55315669/64906879-ec33ff00-d6eb-11e9-930d-23b5434c58f1.png">

**Comment by Fabricio20** [comment]
Hey there, Material was not found means the Material you specified for the item is not valid, can you check on the Material class specific for your version to see if it's correctly named on the config file?

**Comment by TheCoolestPaul** [comment]
Default the WOOL material doesn't work for me, but I changed it to IRON_SWORD and it worked fine.
