### ISSUE TITLE
Flying and Triple Jumps

### ISSUE THREAD

**Issue by drew5494** [Fabricio20/HubBasics#13]
I am able to fly and double jump twice when double tapping the spacebar on my server please fix this.
Thanks.

**Comment by Fabricio20** [comment]
I'm still looking into this, I'm not being able to reproduce the error. Maybe your server was laggy?

**Comment by Fabricio20** [comment]
This Ticket Will Be Re-Opened When The Issue Is Reported Againg. Seems like the code that is being used now is working.
