### ISSUE TITLE
Suggestion: AntiVoid TP Height

### ISSUE THREAD

**Issue by ghost** [Fabricio20/HubBasics#182]
Hello, would it be possible to customize the height the AntiVoid module teleports at? y-64 is a lot of falling before being teleported back. My server software (Purpur) has an option to change the void damage height https://github.com/Fabricio20/HubBasics/issues/170#issuecomment-820329554, but it is not feasible for me to change that for every world. Thanks.

**Comment by Fabricio20** [comment]
Hello, I don't think this is possible, the plugin triggers void tp when the player receives void damage, the only other possibility would be to track the player's Y coordinate, but that's very bad for performance, as I'd have to hook into PlayerMoveEvent.
