### ISSUE TITLE
Command

### ISSUE THREAD

**Issue by RemcoMusic** [Fabricio20/HubBasics#19]
When ever I do a command it opens the chest thing from hubbasic, so when I do /gm 1 it opens the Chest XD Same as for other players

**Comment by Fabricio20** [comment]
Wtf lol

**Comment by Fabricio20** [comment]
I can't reproduce this issue, check if your command is defied WITHOUT /
Example:
Command: 'test'

**Comment by RemcoMusic** [comment]
Yes I found out how to do it now, and everything works fine!! Here is how I have done it now:

http://prntscr.com/7bjv0p
