### ISSUE TITLE
Config Reset

### ISSUE THREAD

**Issue by Miniskateur** [Fabricio20/HubBasics#22]
Hhello, I tried your plugin, it is very complete and godd, but, when I drop the config file in the folder, I restart the server and after that, the config file is reset ...

**Comment by Fabricio20** [comment]
I don't know what is causing that, my config system doesn't have a way of reseting itself, just to create missing values. Check if it's not another plugin that is causing this or maybe you are sending the file to the wrong place.

**Comment by Miniskateur** [comment]
Yeah, I looked for any plugins like modifying tablist but, same like remove it, dosn t work, I send you the config file.
# +----------------------------------------------------+
# <         HubBasics Main Configuration File          >
# <     Documentation Can Be Found On GitHub Page      >
# < Dont forget to add the world at the worlds section >
# +----------------------------------------------------+

JoinEvents:
  DisableMessage: false
  SilentOpJoin: false
  Message: ''
  HubAtLogin: true
  BossBarOnJoin: false
LeaveEvents:
  DisableLeaveMessage: false
  SilentOpLeave: false
  Message: ''
VoidFall:
  Enabled: true
  OnlyHub: false
  Message: '&7Tu as été téléporté au spawn !'
MotdSystem:
  CustomMotd: false
  MoreMotds: false
  Motds:
  - '&c&k&l!!!&r&9&lEvent &c&110 000 abos &f&lSteelorse&r&c&k&l!!!'
ChatAnnouncer:
  Enabled: true
  Msgs:
  - &6Deviens &d&lVIP&r &6et profite des nombreux avantages comme Rencontrer &f&lSteelorse&r &6en privé !
  - &1Soiree &4&l10 000 abos &5&lSteelorse &1!
  Perworld: false
  Worlds:
  - world
  Time: 60

# WARNING This can generate errors since BarAPI is broken.
BossAnnouncer:
  Enabled: false
  Msgs:
  - &3Bienvenue &f&l%p &r&3!
  Perworld: false
  Worlds:
  - Example
  Time: 60
ActionAnnouncer:
  Enabled: false
  Msgs:
  - Announce 1
  - Announce 2
  Perworld: false
  Worlds:
  - Example
  Time: 3
FakePlugins:
  Enabled: true
  Msg: '&fPlugins (5): &aTu&f, &ane&f, &apeux&f, &avoir&f, &ales Plugins !'
BungeeCord:
  Enabled: false
  LobbyServer: lobby
MagicClock:
  Enabled: false
  OnDeath: false
  EnabledInChest: false
  IgnoreBypass: false
  Slot: 5
  AllowMove: false
  NoDrop: false
  Cooldown: 12
  GiveOnWorldChange: false
TitleSystem:
  Enabled: false
  Title: '&cThis Is A Title!'
  Subtitle: '&9This is a Sub-Title!'
BookSystem:
  Enabled: false
  Author: HubBasics
  Name: '&cTha Book'
  Slot: 5
  Give: true
  FirstJoinOnly: true
  Lore:
  - '&bTha lore&c.'
  Pages:
  - '&cThis is a page.'
TabList:
  Enabled: true
  Header: '&1Soiree &4&l10 000 abos &5&lSteelorse &1!'
  Footer: '&aAchète un &bViP &apour nous soutenir !'
HatSystem:
  Enabled: true
  Name: '&aJust A Hat!'
  Lore:
  - '&bTha lore&c.'
  Set: '&cEnjoy your new hat!'
  Removed: '&cYour Hat Was Removed!'
  HatAllowMove: false
  AllowDrops: true
  NoPerm: '&cYou do not have permission for this hat!'

# FOR NOW THIS ONLY WORKS WITH PEX! SORRY!
ChatSystem:
  Enabled: true
  PerWorld: false
  AllowColors: true
  Format: '&e[%w] &f[&2$group&f] &e%p&f: &c%m'
WarpSystem:
  Message: false
  Effect: false
Others:
  DisableRain: false
  DoubleJump: false
  JumpPadBlock: REDSTONE_BLOCK
  JumpPadEnabled: false
  KeepFood: true
  KeepHealth: true
  Stacker: false
  JoinItems: false
  JoinItemsChangeWorld: false
  JoinItemsDeath: false
  ClearInventoryOnEveryWorld: false
  ClearInventory: false
  NoDrops: true
  NoDeathDrops: true
  AllowItemMove: false
  AntiOP: false
  StackerEnabledMessage: '&aStacker Enabled!'
  StackerDisabledMessage: '&cStacker Disabled!'
  FirstJoinItemsOnly: false
  AllowBuilding: true
DisabledCommands:
- example
Worlds:
- world
