### ISSUE TITLE
The config File is reset.

### ISSUE THREAD

**Issue by Miniskateur** [Fabricio20/HubBasics#23]
This is a second post, ok, to try, I remove all the plugins, and keep HubBasics. All the file that I modify are reset to the first basic config after restart server. Jjust the config file, I modify the Tags file, and it work very well.

**Comment by Fabricio20** [comment]
As I said, my plugin doesn't have a method to reset the config. Try parsing your modified config with an yaml parser.

**Comment by Fabricio20** [comment]
Seems like a friend of mine discovered what is happening, under your announcer messages, make sure you have ' around all messages.

**Comment by Fabricio20** [comment]
Seems like more people are having this problem, as reported by one user, it may be your plugin jar being Corrupted, so, before reporting, try reinstalling everything.
