### ISSUE TITLE
JumpPadBlock - Pressure Plates

### ISSUE THREAD

**Issue by Deathinflames** [Fabricio20/HubBasics#25]
When using any type of pressure plate for JumpPadBlock, users must stand on top of it then jump to double jump. Is it possible to make players instantly jump when they move on pressure plate?

**Comment by Fabricio20** [comment]
Pressure plates are not supported by the JumpPadSystem, since I'm doing it using PlayerMoveEvent, maybe in the future I will add support to plates.
