### ISSUE TITLE
Hubbasics Tags conflict with ColoredTags plugin.

### ISSUE THREAD

**Issue by ghost** [Fabricio20/HubBasics#32]
http://i.imgur.com/3ZJcVJ8.jpg

I tried to disable Colored Tab function on config but dont work, have conflict with ColoredTags plugin i think.

Thanks for u support !! :D

**Comment by Fabricio20** [comment]
Thanks for reporting, I'll see what I can do about, for now I suggest that you disable my feature and try NameTagEdit, wich is wayy more updated than ColoredTab, and uses a method that dont break my api.

**Comment by beltez** [comment]
NameTagEdit doesn't work :(

Thanks.
