### ISSUE TITLE
Pct Tick

### ISSUE THREAD

**Issue by Misc4HD** [Fabricio20/HubBasics#36]
![knipsel](https://cloud.githubusercontent.com/assets/3238545/12040779/15d466ee-ae6c-11e5-90a7-56b99d1012bb.PNG)

**Comment by Fabricio20** [comment]
That lag spike will be fixed next update, forgot to make the updater async.

**Comment by Misc4HD** [comment]
Oké thx any idee when the update is comming.

**Comment by Fabricio20** [comment]
Soon, I hope to pull it out this week, if my ISP lets me.
