### ISSUE TITLE
Lots of Problems

### ISSUE THREAD

**Issue by ZombiJesus** [Fabricio20/HubBasics#38]
Hey,

I've recently installed HubBasics for my server and most commands don't seem to work..

- /settings
- /quickwarp

I also believe that those next commands don't work because of Essentials..

- /speed
- /jump

Best Regards,
- ZombiJesus

**Comment by Fabricio20** [comment]
The plugin is undergoing rebuild, and it still may take some time for me to end it.

Regarding the commands, it's probably essentials yes, there is a quick "hack" for this, you might wanna try editing my "plugin.yml" (inside the jar) and add aliases (Which are not used) for all these commands, then save the file and navigate to your commands.yml, edit that file using my aliases, it will end up overriding essentials commands.

Sorry for the trouble!
