### ISSUE TITLE
Many things aren`t working on 1.9.

### ISSUE THREAD

**Issue by Joopie123** [Fabricio20/HubBasics#43]
Hello,

A few days ago i said in a review that jumppads aren`t working, but thats not the only thing thats not working. Here`s a list:

-Players don`t start on the setted hub point when they join the server;
-Jumppads aren`t working;
-Double jump isn`t working;
-Keep food isn`t working;
-Keep health isn`t working;

Can you please take a look at this? I don`t get any errors in the console.

EDIT: All the HubBasics commands, except of /hb, aren`t working! (/settings, etc)

**Comment by Fabricio20** [comment]
/settings is not a command.
Current commands: /hat - /hb - /hub - /sethub

About players not starting on the hub point, I will check it.
Double jump is not finished yet.
Keep health and Keep food are defined on worlds/WorldName.json, make sure those are correctly configured, if they still don't work, I'll do an update to fix it.

**Comment by Joopie123** [comment]
Thank you for your fast reaction! I hope that there will be an update soon!

**Comment by Joopie123** [comment]
Is there already an update? This is the best hub plugin, bur since 1.8 i`ts broken!!

**Comment by Fabricio20** [comment]
There will be an update probably tomorrow, I'm working on getting used to a new IDE/workspace.

**Comment by Joopie123** [comment]
Ok, thank you!

**Comment by Joopie123** [comment]
I don't wanna hurry you, but when do you think there 's an update? I need this plugin so hard, there aren't any other good plugins !!
