### ISSUE TITLE
Error When Jump Pads Are Used

### ISSUE THREAD

**Issue by BungeeTheCookie** [Fabricio20/HubBasics#53]
Hello,
On my server, whenever anyone uses a jump pad, an error occurs. I am running PaperSpigot 1.10 w/ ProtocolSupport. I have a force of 10 for the jump pads.

http://pastebin.com/u7LLHYvU

**Comment by Fabricio20** [comment]
As far as I remember, setting a velocity of 10 is like trying to throw the player to the other side of the map. Try with a lower value (like 3) and tell me how far it goes.

**Comment by BungeeTheCookie** [comment]
@Fabricio20 
Yes, I am trying to throw the player far (as my Hub set up is kind of large), setting it to 3 makes the error go away, but it is not going nearly as far as I want. Thanks for the fast response!

**Comment by Fabricio20** [comment]
Hm, I don't really know how I can help, that is a PaperSpigot (or maybe even Minecraft Server) "error" (more like a warn). It is simply saying that the value that was set for the speed vector is too large.

You can try testing up to 10 and see when you start getting the warnings. (And maybe ask on SpigotMC if there is a way to disable that).

**Comment by BungeeTheCookie** [comment]
Hmm okay. It's just a slight little annoyance seeing that in my console but I'll get by. 

Thank you!
