### ISSUE TITLE
Per world inventories 

### ISSUE THREAD

**Issue by friishon** [Fabricio20/HubBasics#54]
sorry, i don't know in wich place i have to put this.
can you put commands for the items? and que items apear per world.
for example:
join items, could be sand, and has the copan /lobby
if you do right clic, the sand tp to the lobby
and, i would like this item only appears on the world: world
when the item tp me, i would like to appears in other world wich name is lobby
and in lobby i would like to have diferents items.
sorry about my bad english, i'm from spain

**Comment by LorgeN** [comment]
Ok, so basically what you are suggesting is per-world items? Like different inventories per world?

As for the item action stuff, we may make it so you can do this in the future. It is quite a lot of work, and would have to work by you creating the items in the configuration file, and have it execute commands on interaction.

**Comment by friishon** [comment]
thanks
yes like iventories per world
https://www.spigotmc.org/resources/super-lobby-demo-1-8-1-9-1-10-support.20400/ sorry about the spam, this plugin can execute commands with the items, it could be interesting

**Comment by LorgeN** [comment]
Spam is no problem at all, all feedback is very much appreciated! Don't feel like ripping someone off, and commands by items is already in the works. See [CustomItem](https://github.com/Fabricio20/HubBasics/blob/master/HubBasics-Spigot/src/main/java/net/notfab/hubbasics/objects/CustomItem.java) and [CustomItemManager](https://github.com/Fabricio20/HubBasics/blob/master/HubBasics-Spigot/src/main/java/net/notfab/hubbasics/managers/CustomItemManager.java). The thing is we are still working on the config part of this, and will be in the 5.0 update most likely. This will allow creation of menus and such. As to the per world inventories; This would cause an insane amount of delay, lag and similar when switching between worlds on larger servers. Your suggestion has been noted, and again, all feedback is much appreciated.

**Comment by friishon** [comment]
thanks
for the items per world it can use other plugin
your plugin use items in world: world
and other plugin use items in world: the_other_world 
it could be the solution

**Comment by friishon** [comment]
https://www.spigotmc.org/resources/itemjoin.12661/
this plugin have item per world, it use multiverse inventories
and items can execute commands
i hope this plugin can help you

**Comment by LorgeN** [comment]
Again, I appreciate it very much, and I don't want to steal someone's code. I'm currently working on the serialization and deserialization part of the items. The option might be in the next update, if everything goes as planned. As for the inventories, I'm not sure where we stand on that. It seems like a cool feature, but it might have to be it's own plugin due to it being a quite extensive task. 

Repeating my last comment's ending; Your suggestion has been noted, and again, all feedback is much appreciated.
