### ISSUE TITLE
Join_Teleport module

### ISSUE THREAD

**Issue by A248** [Fabricio20/HubBasics#59]
Hello, it seems that the feature "Spawn-On-join" does not work. When executed, it prints out a large amount of console spam. To each plugin, it writes "Could not pass PlayerTeleportEvent to <PLUGIN>," and extra lines of code, or whatever that is. 

At the time, the only things I had done to change my server since the last restart was add more in commands.yml, drop a new plugin (UltraCosmetics) in the plugins directory, and change the Spawn-Join to "enabled: true."

Looking closely at the extra lines of jargon/whatever, I saw that it was caused by HubBasics's Spawn-Join. After disabling the Spawn-Join, this problem never occurred.

I hope this can be fixed.

**Comment by LorgeN** [comment]
Do you mind copying and pasting the error here? Makes debugging much simpler. I have never experienced this error personally, so I dont know what could cause this. Sorry for the very late response, been working on the newest update.

**Comment by LorgeN** [comment]
I managed to recreate the error, but I can't seem to figure out what is causing it. Will look into it further.

**Comment by LorgeN** [comment]
Uh ok, this is embarassing. If you name a world that does not exist, it throws a nullpointer. Which means, all you need to do is specify a world that exists in the configuration file. I added a check for it so people dont run into the same error.
