### ISSUE TITLE
Items Being Deleted

### ISSUE THREAD

**Issue by Chilledchewbacca** [Fabricio20/HubBasics#6]
Hey Fabrico, 

I'm liking the new updates in the plugin, however, i'm still having the same problem as before, when ever the plugin gives items to the player, any items they previously had in those slots get deleted

The plugin is no longer giving out duplicate join items though but it does still duplicate books (however this isnt really a bad thing except they also delete what was in the players slot)

I hope you can nail this bug quickly as i'm eager to start using it on my server asap :)

Thank again,
Adam

**Comment by Fabricio20** [comment]
Working on it.
