### ISSUE TITLE
Gold Pressure Plates rather than Stone

### ISSUE THREAD

**Issue by A248** [Fabricio20/HubBasics#61]
HubBasics has a launch pads feature involved. There is a configurability option to require a pressure plate to be able to be launched via a jump pad. However, this requires a stone pressure plate.

Is there any way to add support for **gold pressure plates**, and not just stone ones?

For example, another option in the config.yml would be "Pressure-plate-type: 1." Pressure plate two could be gold pressure plates. I'm not in any rush to see this feature implemented, because there are no stray redstone blocks around my hub, but I would appreciate it.

Thank you!

(Also, if you could label my thread as an enhancement, that would be nice. It doesn't seem to allow me to.

**Comment by LorgeN** [comment]
Wouldn't be too complicated to accomplish. If we have time to do it, it will be done. Thanks for the feedback, much appreciated!
