### ISSUE TITLE
Commands or Plugin Broken?

### ISSUE THREAD

**Issue by TheAwesomemMutant** [Fabricio20/HubBasics#66]
So, I recently installed a hub plugin. It stopped working. However it was for 1.8. So I got yours because it was updated to 1.10. The commands aren't wrong, they just don't do anything. I fear that it may be because   i'm running a version compatibility plugin. I use viaversion 1.0.1 to do that. Also, my rank plugin isn't working. It worked before, but once i installed this plugin, it doesn't.

**Comment by MrRiptide** [comment]
Do you have the server logs?  Is so, could you please put the log with the error in it and we may be able to help.  The logs should be located in your server directory are /minecraft/logs, and the error is probably in latest.log.
