### ISSUE TITLE
Warps vs EssentialsX

### ISSUE THREAD

**Issue by Sebastian737** [Fabricio20/HubBasics#68]
Hi it's a nice plugin but...
My Essentials Warps don't work beacuse Hubbasics have his warp sistem if I wriite "Load: false"
I give a message like this:'The warps module don't loaded' Pls help! Thanks in advance.

**Comment by Fabricio20** [comment]
Check out how to override the commands using the commands.yml file, I think what you will want is /essentialsx:warp

**Comment by Sebastian737** [comment]
Thanks but if I delete the warps node from config.yml?

**Comment by Sebastian737** [comment]
Maybe not....I can use Hubbascs Warps.I will block warps in my survival lobby.Thanks it's amazing.
