### ISSUE TITLE
Bug "YOU HAVE SPECIFIED A WORLD THAT DOES NOT EXIST IN THE CONFIGURATION FILE"

### ISSUE THREAD

**Issue by CommandActor** [Fabricio20/HubBasics#69]
Hi. Everytime I start the server or try to reload HubBasics, I get this error:
YOU HAVE SPECIFIED A WORLD THAT DOES NOT EXIST IN THE CONFIGURATION FILE

[config.zip](https://github.com/Fabricio20/HubBasics/files/714030/config.zip)
I have no idea why. The world that I specified does exist. I checked it.

**Comment by MrRiptide** [comment]
I'm having this problem too, causing problems like the problem in issue #59.  Do you have Multiverse, and if so, is the plugin trying to load in the middle of multiverse loading the worlds?  That seems to be causing the problem for me, and I don't know how to fix it...

**Comment by Fabricio20** [comment]
If the suggested fix from #74 works, this should no longer be an issue, release is set to deploy in some minutes over at SpigotMC.
