### ISSUE TITLE
[Suggestion] Soft Dependency on Multiverse

### ISSUE THREAD

**Issue by MrRiptide** [Fabricio20/HubBasics#74]
Just a quick suggestion to add a soft dependency for Multiverse, hopefully fixing the bug demonstrated in issue #59 .  This would allow for people to use a multiverse world as the hub.  The bug is caused by Java not being consistent, and when HubBasics loads before Multiverse does, HubBasics will not recognize any worlds made by multiverse, thus causing a NullPointerException.

BTW, I tried it on a personal version, and it seems to have worked by adding the line softdepend: [Multiverse-Core] into the plugins.yml within the jar.  However, I still did get the message telling me that I put in a non-existent world into the config for Join_Teleport, but did not get any NullPointerException messages.

NOTE: This does not mean that all servers running HubBasics must use Multiverse-Core, just that if the server has it, HubBasics will wait for Multiverse to set up before HubBasics will.

Thanks for the great plugin,

MrRiptide

**Comment by Fabricio20** [comment]
While I mist admit I'm late and this project is dead, I think you may have solved this one bug.

Though I'm still not completely sure, since Bukkit tells there is no world, even when itself says it exists, will add the softdepend and I hope it is going to fix this.

**Comment by Fabricio20** [comment]
I will close this since the change has been implemented, if this doesn't fix #69 then we shall discuss another solution in another issue or on #69 itself.
