### ISSUE TITLE
[Suggestion] Choice of where items go under Join-Items

### ISSUE THREAD

**Issue by MrRiptide** [Fabricio20/HubBasics#75]
Just a quick suggestion for the ability to choose which slot you want an item to go into, so you could put something in the 1st slot, 3rd slot, 7th slot, and 9th slot, but have nothing in the other slots.  If there is already a way to do so, please tell me, because air slots won't work...

Thanks for the amazing plugin,

MrRiptide

**Comment by Capri205** [comment]
Yes! This is critically important! e.g Elytra should go in slot #39 and not have the user have to put it there!
