### ISSUE TITLE
[HB Admin] Failed to fetch updates?

### ISSUE THREAD

**Issue by steventrotter** [Fabricio20/HubBasics#79]
Absolutely love this plugin. It does the job of 6 others that I had. However, on /hbreload changes to holograms.yml are not reloaded. Even a server restart does not pull the new data. Any suggestions? I don't want to have to make all of my edits in-game. It is much faster via YAML.

I don't if it is related or not, but on reload and restart I get the following: "[HB Admin] Failed to fetch updates". Thank you!

**Comment by zjjpp** [comment]
this plugin is dead according to author.

**Comment by steventrotter** [comment]
@zjjpp well crap. Do you know of any current, managed substitutes for managing a hub, teleport on join, and holograms?

**Comment by zjjpp** [comment]
no, not really sorry. search on spigotmc.

On Sat, Sep 16, 2017 at 5:23 PM, Steven Trotter <notifications@github.com<mailto:notifications@github.com>> wrote:

@zjjpp<https://github.com/zjjpp> well crap. Do you know of any current, managed substitutes for managing a hub, teleport on join, and holograms?
