### ISSUE TITLE
Integration with Multiverse

### ISSUE THREAD

**Issue by BradFuller** [Fabricio20/HubBasics#8]
Is is possible for different for the plugin only to activate in selected worlds? We use Multiverse, and would like to use some features like no hunger, no health loss and Disable Void Fall but we can't have it activating on every world. For example, the Disable Void Fall part will interrupt Skyblock and things, but we want it on our spawn hub. Thanks.

**Comment by Fabricio20** [comment]
The plugin have an per-world option that is NESCESSARY, so you can put there only the worlds that every function of the plugin will work.
