### ISSUE TITLE
Ability to use Variables

### ISSUE THREAD

**Issue by BradFuller** [Fabricio20/HubBasics#9]
Such as:
%player% : Player's name
%online_players% : Amount of online players
%max_players% : Amount of player slots
%world_player% : Player's world

Thanks

**Comment by Fabricio20** [comment]
Depending where you are using those variables they already exits!

%p = Player's name
& = Color code
%w = World Name

But i'll be adding some others and changing them!

**Comment by Fabricio20** [comment]
Still under development but already added some.
