### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by klmzHC** [Fabricio20/HubBasics#90]
Hi, I installed the plugin on Bungeecord and when I try to perform the /hub or /lobby command it just doesn't do anything, nothing on the logger of the proxy and nothing on the logger of the spigot server.
Furthermore I noticed that when performing /hub-menu command it says "Something happened while executing that HubBasics command". I also tried to rightclick holding the "example-1" item and with the "menu-opener" item and it says "The configured menu is invalid". Since I didn't change anything in the configuration of those files I don't know what could go wrong.
Hope you can help me. Thank you.

**Comment by Redd56** [comment]
Ive noticed thatnfor some reason with bungecord the plugins yaml files are empty so you have to copy paste from the .jar of the plugin itself the other issue idk rn

**Comment by Fabricio20** [comment]
Hey, can you attach the spigot server logs (including startup logs) for me to check that menu issue?

(Also which version you running of HubBasics and SpigotMC?)

**Comment by Fabricio20** [comment]
BungeeCord config generation problems _should_ have been fixed, if they are not I'm gonna take another look.

**Comment by klmzHC** [comment]
> Ive noticed thatnfor some reason with bungecord the plugins yaml files are empty so you have to copy paste from the .jar of the plugin itself the other issue idk rn

I noticed it too and I've already done it. Indeed the first time I run the proxy the plugin doesn't even create the HubBasics folder in plugins folder and it returns this error:

19:35:59 [INFORMAZIONI] Using standard Java JCE cipher.
19:35:59 [INFORMAZIONI] Using standard Java compressor.
19:35:59 [INFORMAZIONI] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.14-SNAPSHOT:9bce837:1408
19:35:59 [INFORMAZIONI] Discovered module: ModuleSpec(name=cmd_alert, file=modules\cmd_alert.jar, provider=JenkinsModuleSource())
19:35:59 [INFORMAZIONI] Discovered module: ModuleSpec(name=cmd_find, file=modules\cmd_find.jar, provider=JenkinsModuleSource())
19:35:59 [INFORMAZIONI] Discovered module: ModuleSpec(name=cmd_list, file=modules\cmd_list.jar, provider=JenkinsModuleSource())
19:35:59 [INFORMAZIONI] Discovered module: ModuleSpec(name=cmd_send, file=modules\cmd_send.jar, provider=JenkinsModuleSource())
19:35:59 [INFORMAZIONI] Discovered module: ModuleSpec(name=cmd_server, file=modules\cmd_server.jar, provider=JenkinsModuleSource())
19:35:59 [INFORMAZIONI] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules\reconnect_yaml.jar, provider=JenkinsModuleSource())
19:35:59 [INFORMAZIONI] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.14-SNAPSHOT:9bce837:1408 by SpigotMC
19:35:59 [INFORMAZIONI] Loaded plugin HubBasics version 6.9.1 by Fabricio20
19:35:59 [INFORMAZIONI] Loaded plugin cmd_find version git:cmd_find:1.14-SNAPSHOT:9bce837:1408 by SpigotMC
19:35:59 [INFORMAZIONI] Loaded plugin SkinsRestorer version 13.6.2 by Th3Tr0LLeR, DoNotSpamPls, Blackfire62
19:35:59 [INFORMAZIONI] Loaded plugin ViaVersion version 2.0.1 by _MylesC, Matsv
19:35:59 [INFORMAZIONI] Loaded plugin cmd_server version git:cmd_server:1.14-SNAPSHOT:9bce837:1408 by SpigotMC
19:35:59 [INFORMAZIONI] Loaded plugin cmd_alert version git:cmd_alert:1.14-SNAPSHOT:9bce837:1408 by SpigotMC
19:35:59 [INFORMAZIONI] Loaded plugin cmd_send version git:cmd_send:1.14-SNAPSHOT:9bce837:1408 by SpigotMC
19:35:59 [INFORMAZIONI] Loaded plugin cmd_list version git:cmd_list:1.14-SNAPSHOT:9bce837:1408 by SpigotMC
19:35:59 [INFORMAZIONI] Loaded plugin BungeeTabListPlus version 2.8.10 by CodeCrafter47
19:35:59 [AVVERTENZA] Forced host server pvp is not defined
19:35:59 [INFORMAZIONI] Enabled plugin reconnect_yaml version git:reconnect_yaml:1.14-SNAPSHOT:9bce837:1408 by SpigotMC
19:35:59 [GRAVE] java.io.IOException: Impossibile trovare il percorso specificato
19:35:59 [GRAVE] 	at java.io.WinNTFileSystem.createFileExclusively(Native Method)
19:35:59 [GRAVE] 	at java.io.File.createNewFile(Unknown Source)
19:35:59 [GRAVE] 	at net.notfab.hubbasics.bungee.managers.ConfigHandler.writeToFile(ConfigHandler.java:41)
19:35:59 [GRAVE] 	at net.notfab.hubbasics.bungee.managers.ConfigHandler.<init>(ConfigHandler.java:13)
19:35:59 [GRAVE] 	at net.notfab.hubbasics.bungee.HubBasics.onEnable(HubBasics.java:24)
19:35:59 [GRAVE] 	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:247)
19:35:59 [GRAVE] 	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:279)
19:35:59 [GRAVE] 	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
19:35:59 [GRAVE] 	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
19:35:59 [GRAVE] java.io.IOException: Impossibile trovare il percorso specificato
19:35:59 [GRAVE] 	at java.io.WinNTFileSystem.createFileExclusively(Native Method)
19:35:59 [GRAVE] 	at java.io.File.createNewFile(Unknown Source)
19:35:59 [GRAVE] 	at net.notfab.hubbasics.bungee.managers.ConfigHandler.writeToFile(ConfigHandler.java:41)
19:35:59 [GRAVE] 	at net.notfab.hubbasics.bungee.managers.ConfigHandler.<init>(ConfigHandler.java:18)
19:35:59 [GRAVE] 	at net.notfab.hubbasics.bungee.HubBasics.onEnable(HubBasics.java:24)
19:35:59 [GRAVE] 	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:247)
19:35:59 [GRAVE] 	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:279)
19:35:59 [GRAVE] 	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
19:35:59 [GRAVE] 	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
19:35:59 [INFORMAZIONI] Enabled plugin HubBasics version 6.9.1 by Fabricio20
19:35:59 [INFORMAZIONI] Enabled plugin cmd_find version git:cmd_find:1.14-SNAPSHOT:9bce837:1408 by SpigotMC
19:36:00 [INFORMAZIONI] Enabled plugin SkinsRestorer version 13.6.2 by Th3Tr0LLeR, DoNotSpamPls, Blackfire62
19:36:00 [INFORMAZIONI] [ViaVersion] Loading 1.12.2 -> 1.13 block mapping...
19:36:00 [INFORMAZIONI] [ViaVersion] Loading 1.12.2 -> 1.13 item mapping...
19:36:00 [INFORMAZIONI] [ViaVersion] Loading new 1.13 tags...
19:36:00 [INFORMAZIONI] [ViaVersion] Loading 1.12.2 -> 1.13 enchantment mapping...
19:36:00 [INFORMAZIONI] [ViaVersion] Loading 1.12.2 -> 1.13 sound mapping...
19:36:00 [INFORMAZIONI] [ViaVersion] Loading translation mappping
19:36:00 [INFORMAZIONI] [ViaVersion] Loading 1.13.2 -> 1.14 blockstate mapping...
19:36:01 [INFORMAZIONI] §f§e[§2SkinsRestorer§e] §a----------------------------------------------
19:36:01 [INFORMAZIONI] §f§e[§2SkinsRestorer§e] §a    +===============+
19:36:01 [INFORMAZIONI] §f§e[§2SkinsRestorer§e] §a    | SkinsRestorer |
19:36:01 [INFORMAZIONI] §f§e[§2SkinsRestorer§e] §a    +===============+
19:36:01 [INFORMAZIONI] §f§e[§2SkinsRestorer§e] §a----------------------------------------------
19:36:01 [INFORMAZIONI] §f§e[§2SkinsRestorer§e] §b    Current version: §a13.6.2
19:36:01 [INFORMAZIONI] §f§e[§2SkinsRestorer§e] §a    This is the latest version!
19:36:01 [INFORMAZIONI] §f§e[§2SkinsRestorer§e] §a----------------------------------------------
19:36:01 [INFORMAZIONI] [ViaVersion] Loading 1.13.2 -> 1.14 block mapping...
19:36:01 [INFORMAZIONI] [ViaVersion] Loading 1.13.2 -> 1.14 item mapping...
19:36:01 [INFORMAZIONI] [ViaVersion] Loading 1.13.2 -> 1.14 sound mapping...
19:36:01 [INFORMAZIONI] [ViaVersion] Loading 1.14 blockstates...
19:36:01 [INFORMAZIONI] [ViaVersion] Loading 1.14 heightmap data...
19:36:01 [INFORMAZIONI] Enabled plugin ViaVersion version 2.0.1 by _MylesC, Matsv
19:36:01 [INFORMAZIONI] [ViaVersion] ViaVersion detected server version: 1.8.x(47)
19:36:01 [INFORMAZIONI] Enabled plugin cmd_server version git:cmd_server:1.14-SNAPSHOT:9bce837:1408 by SpigotMC
19:36:01 [INFORMAZIONI] Enabled plugin cmd_alert version git:cmd_alert:1.14-SNAPSHOT:9bce837:1408 by SpigotMC
19:36:01 [INFORMAZIONI] Enabled plugin cmd_send version git:cmd_send:1.14-SNAPSHOT:9bce837:1408 by SpigotMC
19:36:01 [INFORMAZIONI] Enabled plugin cmd_list version git:cmd_list:1.14-SNAPSHOT:9bce837:1408 by SpigotMC
19:36:01 [INFORMAZIONI] [BungeeTabListPlus] Starting UpdateChecker Task
19:36:01 [INFORMAZIONI] [BungeeTabListPlus] Loading default.yml
19:36:01 [INFORMAZIONI] Enabled plugin BungeeTabListPlus version 2.8.10 by CodeCrafter47
19:36:01 [INFORMAZIONI] Listening on /0.0.0.0:25565
19:36:07 [INFORMAZIONI] Closing listener [id: 0x6b5fc62d, L:/0:0:0:0:0:0:0:0:25565]
19:36:07 [INFORMAZIONI] Closing pending connections
19:36:07 [INFORMAZIONI] Disconnecting 0 connections
19:36:08 [INFORMAZIONI] Disabling plugins
19:36:08 [INFORMAZIONI] Closing IO threads

But it seems like creating the folder and pasting config and messages files do the trick.
Regarding the problem with the menu, since I'm using the plugin on a spigot 1.12.2 server, the default sound "BLOCK_NOTE_BLOCK_PLING" caused the error. For the /hub command problem, it seems like it resolved by itself.
Thank you for your help and I hope that this log can help you with this file-generation issue.
